// Generated by https://quicktype.io

export interface BillResponse {
  mensaje: string;
  data: Data;
}
export interface BillResponseOne {
  mensaje: string;
  data: Bill;
}

export interface Data {
  meta: Meta;
  data: Bill[];
}

export interface Bill {
  id:             number;
  service_id:     number;
  credit_card_id: string;
  status:         number;
  created_at:     string;
  updated_at:     string;
}

export interface BillData {
  service_id:     number;
  credit_card_id: string;
  status:         number;
}

export interface Meta {
  total:             number;
  per_page:          number;
  current_page:      number;
  last_page:         number;
  first_page:        number;
  first_page_url:    string;
  last_page_url:     string;
  next_page_url:     null;
  previous_page_url: null;
}

