// Generated by https://quicktype.io

import { User } from '../ms-security/users.interface';
import { License } from './license.interface';
import { Vehicle } from './vehicle.interface';

export interface DriverResponse {
  mensaje: string;
  data: Data;
}

export interface DriverResponseOne {
  mensaje: string;
  data: Driver;
}

export interface Data {
  meta: Meta;
  data: Driver[];
}

export interface Driver {
  id: number;
  user_id: string;
  is_active: number;
  status: number;
  created_at: string;
  updated_at: string;
  user: User;
  trips: any[];
  license: License | null;
  vehicles: Vehicle[];
}

export interface DriverData {
  user_id: string;
  status: number;
}

export interface Meta {
  total: number;
  per_page: number;
  current_page: number;
  last_page: number;
  first_page: number;
  first_page_url: string;
  last_page_url: string;
  next_page_url: null;
  previous_page_url: null;
}
