// Generated by https://quicktype.io

import { User } from '../ms-security/users.interface';
import { License } from './license.interface';

export interface DriverResponse {
  mensaje: string;
  data: Data;
}

export interface DriverResponseOne {
  mensaje: string;
  data: Driver;
}

export interface Data {
  meta: Meta;
  data: Driver[];
}

export interface Driver {
  id: number;
  user_id: string;
  is_active: number;
  status: number;
  created_at: string;
  updated_at: string;
  user: User;
  trips: any[];
  license: License;
  vehicles: Vehicle[];
}

export interface TotalPermission {
  _id: string;
  route: string;
  method: string;
  description: string;
  status: number;
}

export interface Vehicle {
  id: number;
  driver_id: number;
  license_plate: string;
  model: string;
  capacity: number;
  color: string;
  velocity: number;
  status: number;
  created_at: string;
  updated_at: string;
}

export interface Meta {
  total: number;
  per_page: number;
  current_page: number;
  last_page: number;
  first_page: number;
  first_page_url: string;
  last_page_url: string;
  next_page_url: null;
  previous_page_url: null;
}
