// Generated by https://quicktype.io

export interface DriverResponse {
    mensaje: string;
    data:    Data;
}

export interface Data {
    meta: Meta;
    data: Driver[];
}

export interface Driver {
    id:         number;
    user_id:    string;
    is_active:  number;
    status:     number;
    created_at: string;
    updated_at: string;
    user:       User;
    trips:      any[];
    license:    License | null;
    vehicles:   Vehicle[];
}

export interface License {
    id:              number;
    driver_id:       number;
    expiration_date: string;
    description:     null;
    type:            string;
    status:          number;
    created_at:      string;
    updated_at:      string;
}

export interface User {
    _id:            string;
    email:          string;
    password:       string;
    status:         number;
    created_at:     string;
    twofactor_code: null;
    role:           Role;
    creditCards:    null;
    userProfile:    UserProfile;
}

export interface Role {
    _id:              string;
    name:             string;
    description:      string;
    status:           number;
    totalPermissions: TotalPermission[];
}

export interface TotalPermission {
    _id:         string;
    route:       string;
    method:      string;
    description: string;
    status:      number;
}

export interface UserProfile {
    _id:             string;
    name:            string;
    lastName:        string;
    profilePhoto:    string;
    birthday:        string;
    backgroundImage: string;
    numberPhone:     string;
    status:          number;
}

export interface Vehicle {
    id:            number;
    driver_id:     number;
    license_plate: string;
    model:         string;
    capacity:      number;
    color:         string;
    velocity:      number;
    status:        number;
    created_at:    string;
    updated_at:    string;
}

export interface Meta {
    total:             number;
    per_page:          number;
    current_page:      number;
    last_page:         number;
    first_page:        number;
    first_page_url:    string;
    last_page_url:     string;
    next_page_url:     null;
    previous_page_url: null;
}
