// Generated by https://quicktype.io

import { Driver } from './drivers.interface';

export interface LicenseResponse {
  mensaje: string;
  data: Data;
}

export interface LicenseResponseOne {
  mensaje: string;
  data: License;
}

export interface Data {
  meta: Meta;
  data: License[];
}

export interface License {
  id: number;
  driver_id: number;
  expiration_date: string;
  description: null;
  type: string;
  status: number;
  created_at: string;
  updated_at: string;
  driver: Driver;
}

export interface LicenseData {
  id: number;
  driver_id: number;
  expiration_date: string;
  description: null;
  type: string;
  status: number;
  driver: Driver;
}

export interface Meta {
  total: number;
  per_page: number;
  current_page: number;
  last_page: number;
  first_page: number;
  first_page_url: string;
  last_page_url: string;
  next_page_url: null;
  previous_page_url: null;
}
