// Generated by https://quicktype.io

export interface LicenseResponse {
    mensaje: string;
    data:    Data;
}

export interface Data {
    meta: Meta;
    data: License[];
}

export interface License {
    id:              number;
    driver_id:       number;
    expiration_date: string;
    description:     null;
    type:            string;
    status:          number;
    created_at:      string;
    updated_at:      string;
    driver:          Driver;
}

export interface Driver {
    id:         number;
    user_id:    string;
    is_active:  number;
    status:     number;
    created_at: string;
    updated_at: string;
}

export interface Meta {
    total:             number;
    per_page:          number;
    current_page:      number;
    last_page:         number;
    first_page:        number;
    first_page_url:    string;
    last_page_url:     string;
    next_page_url:     null;
    previous_page_url: null;
}
