// Generated by https://quicktype.io

export interface PointResponse {
    mensaje: string;
    data:    Data;
}

export interface Data {
    meta: Meta;
    data: Point[];
}

export interface Point {
    id:         number;
    latitude:   number;
    longitude:  number;
    status:     number;
    created_at: string;
    updated_at: string;
}

export interface Meta {
    total:             number;
    per_page:          number;
    current_page:      number;
    last_page:         number;
    first_page:        number;
    first_page_url:    string;
    last_page_url:     string;
    next_page_url:     null;
    previous_page_url: null;
}
