// Generated by https://quicktype.io

import { Customer } from './customer.interface';
import { Trip } from './trip.interface';

export interface ServiceResponse {
  mensaje: string;
  data: Data;
}
export interface ServiceResponseOne {
  mensaje: string;
  data: Service;
}

export interface Data {
  meta: Meta;
  data: Service[];
}

export interface Service {
  id: number;
  customer_id: number;
  trip_id: null;
  price: number;
  status: number;
  created_at: null;
  updated_at: string;
  customer: Customer;
  trip: Trip;
  bill: null;
  commentsAndRatings: any[];
}
export interface DataService {
  customer_id: number;
  trip_id?: number;
  price?: number;
  status: number;
  created_at: null;
  updated_at: string;
  customer: Customer;
  trip: Trip;
  bill: null;
  commentsAndRatings: any[];
}

export interface Meta {
  total: number;
  per_page: number;
  current_page: number;
  last_page: number;
  first_page: number;
  first_page_url: string;
  last_page_url: string;
  next_page_url: null;
  previous_page_url: null;
}
