// Generated by https://quicktype.io

export interface TripResponse {
  mensaje: string;
  data: Data;
}

export interface Data {
  meta: Meta;
  data: Trip[];
}

export interface Trip {
  id: number;
  driver_id: number;
  started_at: string;
  finished_at: string;
  distance: number;
  status: number;
  created_at: string;
  updated_at: string;
  driver: Driver;
  service: null;
  points: Point[];
}

export interface Driver {
  id: number;
  user_id: string;
  is_active: number;
  status: number;
  created_at: string;
  updated_at: string;
}

export interface Point {
  id: number;
  latitude: number;
  longitude: number;
  status: number;
  created_at: string;
  updated_at: string;
}

export interface Meta {
  total: number;
  per_page: number;
  current_page: number;
  last_page: number;
  first_page: number;
  first_page_url: string;
  last_page_url: string;
  next_page_url: null;
  previous_page_url: null;
}
